# Site settings
title: Solar Rogue
email: ombarus.dev@gmail.com
url: https://ombarus.com/
description: "Solar rogue is a space exploration adventure in the purest tradition of roguelike. Featuring procedurally generated solar systems, perma-death, tactical turned-based gameplay and a variety of ships, planets and ennemy to challenge!"
keywords: "Ombarus, Solar Rogue, Roguelike, Video Game, Mobile, Mobile App, PC, Steam, Itch.io, Tactical, Turn-Based"
skills: "Turn-Based Space Opera"
meta_author: Bouvier Guillaume

# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Contact form:
# - static : pass through formspree.io to validate email sending
# - disqus : replace contact form by disqus thread
# - comment the line below if you want to stick with the default PHP contact form
contact: static

# If you use disqus you need disqus shortname
# https://help.disqus.com/customer/portal/articles/466208
disqus_shortname: myshortname

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 283845 #1481ba light blue
  primary-alt: B5BEC6 #034748 dark green #3A506B puple blue
  primary-rgb: "9,9,8"
  secondary: 090908
  secondary-dark: 2b2b2b

# Footer settings
footer:
  copyright: Ombarus
  location: Japan
  social: Around the Web
  credits: Credits

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: youtube
    url: https://www.youtube.com/channel/UCscoqrVcMbZwv5jIpKVYpDg/featured?view_as=subscriber
  - title: twitter
    url: https://twitter.com/Ombarus1
  - title: linkedin
    url: https://www.linkedin.com/in/guillaume-bouvier-88a4863/
  - title: github
    url: https://github.com/Ombarus
  - title: patreon
    url: http://www.patreon.com/ombarus
  - title: instagram
    url: http://www.instagram.com/ombarus1

# Postal address (add as many lines as necessary)
address:
  - line: Contact me by email.

# Credits content
credits: 'All content therein is owned by their respective creator. Please ask before you copy, distribute or reproduce anything you find on this website.'

# Build settings
markdown: kramdown
permalink: pretty
